### ISSUE TITLE
missing files 

### ISSUE THREAD

**Issue by rahultah** [sid113/AI-Based-Voice-Prescription#1]
Below listed are some missing files. Can you please add the files so that the application works

ilename_words = "data/words.txt"
filename_tags = "data/tags.txt"
filename_chars = "data/chars.txt"

**Comment by sid113** [comment]
Hi @rahultah, 
You can find the trained model at **ai-based-voice-prescription/voice-prescription-fastapi-main/model/**. You can use that model directly. And regarding the files, we have used those files under the service agreement. But you can download those files from
[https://n2c2.dbmi.hms.harvard.edu/data-use-agreement](url). You just have to fill the form. 
Hope this helps.

**Comment by sid113** [comment]
Hi @rahultah 
We have used the files under the service agreement. However, you can download those files from [https://n2c2.dbmi.hms.harvard.edu/data-use-agreement](url) 
Also, you can use the trained model from **http://ai-based-voice-prescription/voice-prescription-fastapi-main/results/test/saves/**

Hope this helps.

**Comment by inctechy07** [comment]
> Below listed are some missing files. Can you please add the files so that the application works
> 
> ilename_words = "data/words.txt" filename_tags = "data/tags.txt" filename_chars = "data/chars.txt"

brother from where should i find this yes even i have this error
