### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by pratik1719** [sid113/AI-Based-Voice-Prescription#2]
getting error
![image](https://user-images.githubusercontent.com/56343832/163703157-0e32b879-b3e9-4fca-9176-7a0c83573d6e.png)

**Comment by disha2000** [comment]
Can you please elaborate more on what point did you get this error? 
So that our team will solve this issue.

**Comment by disha2000** [comment]
Hey! 
You need to add a .env file. In this file, add the following variables.

```
MONGODB_CONNECTION_STRING = <Mongodb conenction>
SECRET=yWbS38U8t9FMQn6uPV
EMAIL_ID= <email id>
PASSWORD=<password>
```

Note:
EMAIL_ID and PASSWORD are optional fields.

To create a MongoDB connection you can refer to this video: 
https://www.youtube.com/watch?v=St0_qSe7RCE&list=PLJM1tXwlGdaf57oUx0rIqSW668Rpo_7oU&index=2&ab_channel=Devistry

I hope this will help you
